import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Home from '@/components/Home'


const inter = Inter({ subsets: ['latin'] })

export default function App({courseList}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home courseList={courseList}/>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:2000/course/user-course/list');
  const courseList = await res.json()

  
  return { props: { courseList } }
}


